[clarify.bstr]
version = "=1"
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "COPYING", hash = 0x278afbcf },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x462dee44 },
    { path = "src/unicode/data/LICENSE-UNICODE", hash = 0x70f7339  },
]

[clarify.petgraph]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xc97e30bd },
]
skip-files = [
    # this license applies to graphical assets which we do not distribute
    "assets/LICENSE.md",
]

[clarify.regex-syntax]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "src/unicode_tables/LICENSE-UNICODE", hash = 0xa7f28b93 },
]

[clarify.rust-fuzzy-search]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0xbde481e5 },
    { path = "LICENSE-MIT", hash = 0xb5a90d39 },
]
skip-files = [
    # these licenses apply to documentation
    "target/doc/FiraSans-LICENSE.txt",
    "target/doc/COPYRIGHT.txt",
    "target/doc/LICENSE-APACHE.txt",
    "target/doc/LICENSE-MIT.txt",
    "target/doc/SourceCodePro-LICENSE.txt",
    "target/doc/SourceSerif4-LICENSE.md",
]


[clarify.typenum]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x91d5a0a7 },
    { path = "LICENSE-MIT", hash = 0xb9f15462 },
    { path = "LICENSE", hash = 0xa4618a29 },
]

[clarify.unicode-ident]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0xb5518783 },
    { path = "LICENSE-MIT", hash = 0x386ca1bc },
    { path = "LICENSE-UNICODE", hash = 0x9698cbbe },
]
